all: binsh_1 binsh_2 binsh_gets

binsh_1:
	nasm -o binsh_1 binsh_1.asm

binsh_2:
	nasm -o binsh_2 binsh_2.asm

binsh_gets:
	nasm -o binsh_gets binsh_gets.asm

clean:
	rm binsh_1 binsh_2 binsh_gets


.PHONY: clean all