import os


PandocBuilder = Builder(action = "pandoc $SOURCES --listings --toc --toc-depth=5 --include-in-header ./titlesec.tex -o $TARGET",
                          suffix = ".pdf",
                          src_suffix = ".md")


env = Environment(BUILDERS={"Pandoc": PandocBuilder}, 
                  ENV=os.environ)


SConscript('diags/SConstruct')


for md in Glob("*.md"):
    env.Pandoc(md)
