all: heap0 heap1 heap2 heap3

heap0:
	gcc -o heap0 heap0.c

heap1:
	gcc -o heap1 heap1.c

heap2:
	gcc -o heap2 heap2.c

heap3:
	gcc -o heap3 heap3.c

clean:
	rm heap0 heap1 heap2 heap3


.PHONY: clean all