import os


Seq2SVGBuilder = Builder(action="diagrams sequence $SOURCES $TARGET",
                         suffix=".svg",
                         src_suffix=".sequence")
Flow2SVGBuilder = Builder(action="diagrams flowchart $SOURCES $TARGET",
                          suffix=".svg",
                          src_suffix=".flowchart")
SVG2PNGBuilder = Builder(action="inkscape -z -e $TARGET -w 1000 $SOURCES",
                         suffix=".png",
                         src_suffix=".svg")

env = Environment(BUILDERS={"Seq2SVG": Seq2SVGBuilder,
                            "SVG2PNG": SVG2PNGBuilder,
                            "Flow2SVG": Flow2SVGBuilder}, 
                  ENV=os.environ)


for seq in Glob("*.sequence"):
    env.SVG2PNG(env.Seq2SVG(seq))

for fl in Glob("*.flowchart"):
    env.SVG2PNG(env.Flow2SVG(fl))
